export const COUNTRY_NUMBER_OPTIONS = [
  {
    label_kr: '가나 (+233)',
    label_en: 'Ghana (+233)',
    value: '+233',
    code: 'Ghana (+233)',
  },
  {
    label_kr: '가봉 (+241)',
    label_en: 'Gabon (+241)',
    value: '+241',
    code: 'Gabon (+241)',
  },
  {
    label_kr: '가이아나 (+592)',
    label_en: 'Guyana (+592)',
    value: '+592',
    code: 'Guyana (+592)',
  },
  {
    label_kr: '감비아 (+220)',
    label_en: 'Gambia (+220)',
    value: '+220',
    code: 'Gambia (+220)',
  },
  {
    label_kr: '건지 (+44)',
    label_en: 'Guernsey (+44)',
    value: '+44',
    code: 'Guernsey (+44)',
  },
  {
    label_kr: '과들루프 (+590)',
    label_en: 'Guadeloupe (+590)',
    value: '+590',
    code: 'Guadeloupe (+590)',
  },
  {
    label_kr: '과테말라 (+502)',
    label_en: 'Guatemala (+502)',
    value: '+502',
    code: 'Guatemala (+502)',
  },
  {
    label_kr: '괌 (+1-671)',
    label_en: 'Guam (+1-671)',
    value: '+1-671',
    code: 'Guam (+1-671)',
  },
  {
    label_kr: '교황청 (+379)',
    label_en: 'Vatican City (+379)',
    value: '+379',
    code: 'Vatican City (+379)',
  },
  {
    label_kr: '그레나다 (+1-473)',
    label_en: 'Grenada (+1-473)',
    value: '+1-473',
    code: 'Grenada (+1-473)',
  },
  {
    label_kr: '그리스 (+30)',
    label_en: 'Greece (+30)',
    value: '+30',
    code: 'Greece (+30)',
  },
  {
    label_kr: '그린란드 (+299)',
    label_en: 'Greenland (+299)',
    value: '+299',
    code: 'Greenland (+299)',
  },
  {
    label_kr: '기니 (+224)',
    label_en: 'Guinea (+224)',
    value: '+224',
    code: 'Guinea (+224)',
  },
  {
    label_kr: '기니+Bissau (+245)',
    label_en: 'Guinea+Bissau (+245)',
    value: '+245',
    code: 'Guinea+Bissau (+245)',
  },
  {
    label_kr: '나미비아 (+264)',
    label_en: 'Namibia (+264)',
    value: '+264',
    code: 'Namibia (+264)',
  },
  {
    label_kr: '나우루 (+674)',
    label_en: 'Nauru (+674)',
    value: '+674',
    code: 'Nauru (+674)',
  },
  {
    label_kr: '나이지리아 (+234)',
    label_en: 'Nigeria (+234)',
    value: '+234',
    code: 'Nigeria (+234)',
  },
  {
    label_kr: '남수단 (+211)',
    label_en: 'South Sudan (+211)',
    value: '+211',
    code: 'South Sudan (+211)',
  },
  {
    label_kr: '남아프리카공화국 (+27)',
    label_en: 'South Africa (+27)',
    value: '+27',
    code: 'South Africa (+27)',
  },
  {
    label_kr: '네덜란드 (+31)',
    label_en: 'Netherlands (+31)',
    value: '+31',
    code: 'Netherlands (+31)',
  },
  {
    label_kr: '네덜란드령 안틸레스 (+599)',
    label_en: 'Netherlands Antilles (+599)',
    value: '+599',
    code: 'Netherlands Antilles (+599)',
  },
  {
    label_kr: '네팔 (+977)',
    label_en: 'Nepal (+977)',
    value: '+977',
    code: 'Nepal (+977)',
  },
  {
    label_kr: '노르웨이 (+47)',
    label_en: 'Norway (+47)',
    value: '+47',
    code: 'Norway (+47)',
  },
  {
    label_kr: '뉴 칼레도니아 (+687)',
    label_en: 'New Caledonia (+687)',
    value: '+687',
    code: 'New Caledonia (+687)',
  },
  {
    label_kr: '뉴질랜드 (+64)',
    label_en: 'New Zealand (+64)',
    value: '+64',
    code: 'New Zealand (+64)',
  },
  {
    label_kr: '니우에 (+683)',
    label_en: 'Niue (+683)',
    value: '+683',
    code: 'Niue (+683)',
  },
  {
    label_kr: '니제르 (+227)',
    label_en: 'Niger (+227)',
    value: '+227',
    code: 'Niger (+227)',
  },
  {
    label_kr: '니카라과 (+505)',
    label_en: 'Nicaragua (+505)',
    value: '+505',
    code: 'Nicaragua (+505)',
  },
  {
    label_kr: '대한민국 (+82)',
    label_en: 'South Korea (+82)',
    value: '+82',
    code: 'South Korea (+82)',
  },
  {
    label_kr: '덴마크 (+45)',
    label_en: 'Denmark (+45)',
    value: '+45',
    code: 'Denmark (+45)',
  },
  {
    label_kr: '도미니카공화국 (+1-809)',
    label_en: 'Dominican Republic (+1-809)',
    value: '+1-809',
    code: 'Dominican Republic (+1-809)',
  },
  {
    label_kr: '도미니카연방 (+1-767)',
    label_en: 'Dominica (+1-767)',
    value: '+1-767',
    code: 'Dominica (+1-767)',
  },
  {
    label_kr: '독일 (+49)',
    label_en: 'Germany (+49)',
    value: '+49',
    code: 'Germany (+49)',
  },
  {
    label_kr: '동티모르 (+670)',
    label_en: 'East Timor (+670)',
    value: '+670',
    code: 'East Timor (+670)',
  },
  {
    label_kr: '라오스 (+856)',
    label_en: 'Laos (+856)',
    value: '+856',
    code: 'Laos (+856)',
  },
  {
    label_kr: '라이베리아 (+231)',
    label_en: 'Liberia (+231)',
    value: '+231',
    code: 'Liberia (+231)',
  },
  {
    label_kr: '라트비아 (+371)',
    label_en: 'Latvia (+371)',
    value: '+371',
    code: 'Latvia (+371)',
  },
  {
    label_kr: '러시아 (+7)',
    label_en: 'Russia (+7)',
    value: '+7',
    code: 'Russia (+7)',
  },
  {
    label_kr: '레바논 (+961)',
    label_en: 'Lebanon (+961)',
    value: '+961',
    code: 'Lebanon (+961)',
  },
  {
    label_kr: '레소토 (+266)',
    label_en: 'Lesotho (+266)',
    value: '+266',
    code: 'Lesotho (+266)',
  },
  {
    label_kr: '레위니옹 (+262)',
    label_en: 'Réunion (+262)',
    value: '+262',
    code: 'Réunion (+262)',
  },
  {
    label_kr: '루마니아 (+40)',
    label_en: 'Romania (+40)',
    value: '+40',
    code: 'Romania (+40)',
  },
  {
    label_kr: '룩셈부르크 (+352)',
    label_en: 'Luxembourg (+352)',
    value: '+352',
    code: 'Luxembourg (+352)',
  },
  {
    label_kr: '르완다 (+250)',
    label_en: 'Rwanda (+250)',
    value: '+250',
    code: 'Rwanda (+250)',
  },
  {
    label_kr: '리비아 (+218)',
    label_en: 'Libya (+218)',
    value: '+218',
    code: 'Libya (+218)',
  },
  {
    label_kr: '리투아니아 (+370)',
    label_en: 'Lithuania (+370)',
    value: '+370',
    code: 'Lithuania (+370)',
  },
  {
    label_kr: '리히텐슈타인 (+423)',
    label_en: 'Liechtenstein (+423)',
    value: '+423',
    code: 'Liechtenstein (+423)',
  },
  {
    label_kr: '마다가스카르 (+261)',
    label_en: 'Madagascar (+261)',
    value: '+261',
    code: 'Madagascar (+261)',
  },
  {
    label_kr: '마르티니크 (+596)',
    label_en: 'Martinique (+596)',
    value: '+596',
    code: 'Martinique (+596)',
  },
  {
    label_kr: '마셜제도 (+692)',
    label_en: 'Marshall Islands (+692)',
    value: '+692',
    code: 'Marshall Islands (+692)',
  },
  {
    label_kr: '마요트 (+262)',
    label_en: 'Mayotte (+262)',
    value: '+262',
    code: 'Mayotte (+262)',
  },
  {
    label_kr: '마이크로네시아연방 (+691)',
    label_en: 'Micronesia (+691)',
    value: '+691',
    code: 'Micronesia (+691)',
  },
  {
    label_kr: '마카오 (+853)',
    label_en: 'Macau (+853)',
    value: '+853',
    code: 'Macau (+853)',
  },
  {
    label_kr: '말라위 (+265)',
    label_en: 'Malawi (+265)',
    value: '+265',
    code: 'Malawi (+265)',
  },
  {
    label_kr: '말레이시아 (+60)',
    label_en: 'Malaysia (+60)',
    value: '+60',
    code: 'Malaysia (+60)',
  },
  {
    label_kr: '말리 (+223)',
    label_en: 'Mali (+223)',
    value: '+223',
    code: 'Mali (+223)',
  },
  {
    label_kr: '맨 섬 (+44)',
    label_en: 'Isle of Man (+44)',
    value: '+44',
    code: 'Isle of Man (+44)',
  },
  {
    label_kr: '멕시코 (+52)',
    label_en: 'Mexico (+52)',
    value: '+52',
    code: 'Mexico (+52)',
  },
  {
    label_kr: '모나코 (+377)',
    label_en: 'Monaco (+377)',
    value: '+377',
    code: 'Monaco (+377)',
  },
  {
    label_kr: '모로코 (+212)',
    label_en: 'Morocco (+212)',
    value: '+212',
    code: 'Morocco (+212)',
  },
  {
    label_kr: '모리셔스 (+230)',
    label_en: 'Mauritius (+230)',
    value: '+230',
    code: 'Mauritius (+230)',
  },
  {
    label_kr: '모리타니아 (+222)',
    label_en: 'Mauritania (+222)',
    value: '+222',
    code: 'Mauritania (+222)',
  },
  {
    label_kr: '모잠비크 (+258)',
    label_en: 'Mozambique (+258)',
    value: '+258',
    code: 'Mozambique (+258)',
  },
  {
    label_kr: '몬테네그로 (+382)',
    label_en: 'Montenegro (+382)',
    value: '+382',
    code: 'Montenegro (+382)',
  },
  {
    label_kr: '몬트세랫 (+1-664)',
    label_en: 'Montserrat (+1-664)',
    value: '+1-664',
    code: 'Montserrat (+1-664)',
  },
  {
    label_kr: '몰도바 (+373)',
    label_en: 'Moldova (+373)',
    value: '+373',
    code: 'Moldova (+373)',
  },
  {
    label_kr: '몰디브 (+960)',
    label_en: 'Maldives (+960)',
    value: '+960',
    code: 'Maldives (+960)',
  },
  {
    label_kr: '몰타 (+356)',
    label_en: 'Malta (+356)',
    value: '+356',
    code: 'Malta (+356)',
  },
  {
    label_kr: '몽골 (+976)',
    label_en: 'Mongolia (+976)',
    value: '+976',
    code: 'Mongolia (+976)',
  },
  {
    label_kr: '미국 (+1)',
    label_en: 'United States (+1)',
    value: '+1',
    code: 'United States (+1)',
  },
  {
    label_kr: '미얀마 (+95)',
    label_en: 'Myanmar (+95)',
    value: '+95',
    code: 'Myanmar (+95)',
  },
  {
    label_kr: '바누아투 (+678)',
    label_en: 'Vanuatu (+678)',
    value: '+678',
    code: 'Vanuatu (+678)',
  },
  {
    label_kr: '바레인 (+973)',
    label_en: 'Bahrain (+973)',
    value: '+973',
    code: 'Bahrain (+973)',
  },
  {
    label_kr: '바베이도스 (+1-246)',
    label_en: 'Barbados (+1-246)',
    value: '+1-246',
    code: 'Barbados (+1-246)',
  },
  {
    label_kr: '바하마 (+1-242)',
    label_en: 'Bahamas (+1-242)',
    value: '+1-242',
    code: 'Bahamas (+1-242)',
  },
  {
    label_kr: '방글라데시 (+880)',
    label_en: 'Bangladesh (+880)',
    value: '+880',
    code: 'Bangladesh (+880)',
  },
  {
    label_kr: '버뮤다 (+1-441)',
    label_en: 'Bermuda (+1-441)',
    value: '+1-441',
    code: 'Bermuda (+1-441)',
  },
  {
    label_kr: '베냉 (+229)',
    label_en: 'Benin (+229)',
    value: '+229',
    code: 'Benin (+229)',
  },
  {
    label_kr: '베네수엘라 (+58)',
    label_en: 'Venezuela (+58)',
    value: '+58',
    code: 'Venezuela (+58)',
  },
  {
    label_kr: '베트남 (+84)',
    label_en: 'Vietnam (+84)',
    value: '+84',
    code: 'Vietnam (+84)',
  },
  {
    label_kr: '벨기에 (+32)',
    label_en: 'Belgium (+32)',
    value: '+32',
    code: 'Belgium (+32)',
  },
  {
    label_kr: '벨라루스 (+375)',
    label_en: 'Belarus (+375)',
    value: '+375',
    code: 'Belarus (+375)',
  },
  {
    label_kr: '벨리즈 (+501)',
    label_en: 'Belize (+501)',
    value: '+501',
    code: 'Belize (+501)',
  },
  {
    label_kr: '보스니아헤르체고비나 (+387)',
    label_en: 'Bosnia and Herzegovina (+387)',
    value: '+387',
    code: 'Bosnia and Herzegovina (+387)',
  },
  {
    label_kr: '보츠와나 (+267)',
    label_en: 'Botswana (+267)',
    value: '+267',
    code: 'Botswana (+267)',
  },
  {
    label_kr: '볼리비아 (+591)',
    label_en: 'Bolivia (+591)',
    value: '+591',
    code: 'Bolivia (+591)',
  },
  {
    label_kr: '부룬디 (+257)',
    label_en: 'Burundi (+257)',
    value: '+257',
    code: 'Burundi (+257)',
  },
  {
    label_kr: '부르키나파소 (+226)',
    label_en: 'Burkina Faso (+226)',
    value: '+226',
    code: 'Burkina Faso (+226)',
  },
  {
    label_kr: '부탄 (+975)',
    label_en: 'Bhutan (+975)',
    value: '+975',
    code: 'Bhutan (+975)',
  },
  {
    label_kr: '북마리아나 군도 (+1-670)',
    label_en: 'Northern Mariana Islands (+1-670)',
    value: '+1-670',
    code: 'Northern Mariana Islands (+1-670)',
  },
  {
    label_kr: '북마케도니아 (+389)',
    label_en: 'North Macedonia (+389)',
    value: '+389',
    code: 'North Macedonia (+389)',
  },
  {
    label_kr: '불가리아 (+359)',
    label_en: 'Bulgaria (+359)',
    value: '+359',
    code: 'Bulgaria (+359)',
  },
  {
    label_kr: '브라질 (+55)',
    label_en: 'Brazil (+55)',
    value: '+55',
    code: 'Brazil (+55)',
  },
  {
    label_kr: '브루나이 (+673)',
    label_en: 'Brunei (+673)',
    value: '+673',
    code: 'Brunei (+673)',
  },
  {
    label_kr: '사모아 (+685)',
    label_en: 'Samoa (+685)',
    value: '+685',
    code: 'Samoa (+685)',
  },
  {
    label_kr: '사우디아라비아 (+966)',
    label_en: 'Saudi Arabia (+966)',
    value: '+966',
    code: 'Saudi Arabia (+966)',
  },
  {
    label_kr: '사이프러스 (+357)',
    label_en: 'Cyprus (+357)',
    value: '+357',
    code: 'Cyprus (+357)',
  },
  {
    label_kr: '사하라 아랍민주공화국 (서부사하라) (+212)',
    label_en: 'Western Sahara (+212)',
    value: '+212',
    code: 'Western Sahara (+212)',
  },
  {
    label_kr: '산마리노 (+378)',
    label_en: 'San Marino (+378)',
    value: '+378',
    code: 'San Marino (+378)',
  },
  {
    label_kr: '상투메프린시페 (+239)',
    label_en: 'São Tomé and Príncipe (+239)',
    value: '+239',
    code: 'São Tomé and Príncipe (+239)',
  },
  {
    label_kr: '생피에르·미클롱 (+508)',
    label_en: 'Saint Pierre and Miquelon (+508)',
    value: '+508',
    code: 'Saint Pierre and Miquelon (+508)',
  },
  {
    label_kr: '세네갈 (+221)',
    label_en: 'Senegal (+221)',
    value: '+221',
    code: 'Senegal (+221)',
  },
  {
    label_kr: '세르비아 (+381)',
    label_en: 'Serbia (+381)',
    value: '+381',
    code: 'Serbia (+381)',
  },
  {
    label_kr: '세이셸 (+248)',
    label_en: 'Seychelles (+248)',
    value: '+248',
    code: 'Seychelles (+248)',
  },
  {
    label_kr: '세인트 루시아 (+1-758)',
    label_en: 'Saint Lucia (+1-758)',
    value: '+1-758',
    code: 'Saint Lucia (+1-758)',
  },
  {
    label_kr: '세인트 빈센트 그레나딘 (+1-784)',
    label_en: 'Saint Vincent and the Grenadines (+1-784)',
    value: '+1-784',
    code: 'Saint Vincent and the Grenadines (+1-784)',
  },
  {
    label_kr: '세인트 키츠 네비스 (+1-869)',
    label_en: 'Saint Kitts and Nevis (+1-869)',
    value: '+1-869',
    code: 'Saint Kitts and Nevis (+1-869)',
  },
  {
    label_kr: '세인트 헬레나 섬 (+290)',
    label_en: 'Saint Helena (+290)',
    value: '+290',
    code: 'Saint Helena (+290)',
  },
  {
    label_kr: '소말리아 (+252)',
    label_en: 'Somalia (+252)',
    value: '+252',
    code: 'Somalia (+252)',
  },
  {
    label_kr: '솔로몬제도 (+677)',
    label_en: 'Solomon Islands (+677)',
    value: '+677',
    code: 'Solomon Islands (+677)',
  },
  {
    label_kr: '수단 (+249)',
    label_en: 'Sudan (+249)',
    value: '+249',
    code: 'Sudan (+249)',
  },
  {
    label_kr: '수리남 (+597)',
    label_en: 'Suriname (+597)',
    value: '+597',
    code: 'Suriname (+597)',
  },
  {
    label_kr: '스리랑카 (+94)',
    label_en: 'Sri Lanka (+94)',
    value: '+94',
    code: 'Sri Lanka (+94)',
  },
  {
    label_kr: '스웨덴 (+46)',
    label_en: 'Sweden (+46)',
    value: '+46',
    code: 'Sweden (+46)',
  },
  {
    label_kr: '스위스 (+41)',
    label_en: 'Switzerland (+41)',
    value: '+41',
    code: 'Switzerland (+41)',
  },
  {
    label_kr: '스페인 (+34)',
    label_en: 'Spain (+34)',
    value: '+34',
    code: 'Spain (+34)',
  },
  {
    label_kr: '슬로바키아 (+421)',
    label_en: 'Slovakia (+421)',
    value: '+421',
    code: 'Slovakia (+421)',
  },
  {
    label_kr: '슬로베니아 (+386)',
    label_en: 'Slovenia (+386)',
    value: '+386',
    code: 'Slovenia (+386)',
  },
  {
    label_kr: '시리아 (+963)',
    label_en: 'Syria (+963)',
    value: '+963',
    code: 'Syria (+963)',
  },
  {
    label_kr: '시에라리온 (+232)',
    label_en: 'Sierra Leone (+232)',
    value: '+232',
    code: 'Sierra Leone (+232)',
  },
  {
    label_kr: '싱가포르 (+65)',
    label_en: 'Singapore (+65)',
    value: '+65',
    code: 'Singapore (+65)',
  },
  {
    label_kr: '아랍에미리트 (+971)',
    label_en: 'United Arab Emirates (+971)',
    value: '+971',
    code: 'United Arab Emirates (+971)',
  },
  {
    label_kr: '아루바 (+297)',
    label_en: 'Aruba (+297)',
    value: '+297',
    code: 'Aruba (+297)',
  },
  {
    label_kr: '아르메니아 (+374)',
    label_en: 'Armenia (+374)',
    value: '+374',
    code: 'Armenia (+374)',
  },
  {
    label_kr: '아르헨티나 (+54)',
    label_en: 'Argentina (+54)',
    value: '+54',
    code: 'Argentina (+54)',
  },
  {
    label_kr: '아이슬란드 (+354)',
    label_en: 'Iceland (+354)',
    value: '+354',
    code: 'Iceland (+354)',
  },
  {
    label_kr: '아이티 (+509)',
    label_en: 'Haiti (+509)',
    value: '+509',
    code: 'Haiti (+509)',
  },
  {
    label_kr: '아일랜드 (+353)',
    label_en: 'Ireland (+353)',
    value: '+353',
    code: 'Ireland (+353)',
  },
  {
    label_kr: '아제르바이잔 (+994)',
    label_en: 'Azerbaijan (+994)',
    value: '+994',
    code: 'Azerbaijan (+994)',
  },
  {
    label_kr: '아프가니스탄 (+93)',
    label_en: 'Afghanistan (+93)',
    value: '+93',
    code: 'Afghanistan (+93)',
  },
  {
    label_kr: '안도라 (+376)',
    label_en: 'Andorra (+376)',
    value: '+376',
    code: 'Andorra (+376)',
  },
  {
    label_kr: '알바니아 (+355)',
    label_en: 'Albania (+355)',
    value: '+355',
    code: 'Albania (+355)',
  },
  {
    label_kr: '알제리 (+213)',
    label_en: 'Algeria (+213)',
    value: '+213',
    code: 'Algeria (+213)',
  },
  {
    label_kr: '앙골라 (+244)',
    label_en: 'Angola (+244)',
    value: '+244',
    code: 'Angola (+244)',
  },
  {
    label_kr: '앤티가바부다 (+1-869)',
    label_en: 'Antigua and Barbuda (+1-869)',
    value: '+1-869',
    code: 'Antigua and Barbuda (+1-869)',
  },
  {
    label_kr: '앵귈라 (+1-264)',
    label_en: 'Anguilla (+1-264)',
    value: '+1-264',
    code: 'Anguilla (+1-264)',
  },
  {
    label_kr: '에리트레아 (+291)',
    label_en: 'Eritrea (+291)',
    value: '+291',
    code: 'Eritrea (+291)',
  },
  {
    label_kr: '에스와티니 (+268)',
    label_en: 'Eswatini (+268)',
    value: '+268',
    code: 'Eswatini (+268)',
  },
  {
    label_kr: '에스토니아 (+372)',
    label_en: 'Estonia (+372)',
    value: '+372',
    code: 'Estonia (+372)',
  },
  {
    label_kr: '에콰도르 (+593)',
    label_en: 'Ecuador (+593)',
    value: '+593',
    code: 'Ecuador (+593)',
  },
  {
    label_kr: '에티오피아 (+251)',
    label_en: 'Ethiopia (+251)',
    value: '+251',
    code: 'Ethiopia (+251)',
  },
  {
    label_kr: '엘살바도르 (+503)',
    label_en: 'El Salvador (+503)',
    value: '+503',
    code: 'El Salvador (+503)',
  },
  {
    label_kr: '영국 (+44)',
    label_en: 'United Kingdom (+44)',
    value: '+44',
    code: 'United Kingdom (+44)',
  },
  {
    label_kr: '영국령 남극지역 (+672)',
    label_en: 'British Antarctic Territory (+672)',
    value: '+672',
    code: 'British Antarctic Territory (+672)',
  },
  {
    label_kr: '영국령 버진 아일랜드 (+1-284)',
    label_en: 'British Virgin Islands (+1-284)',
    value: '+1-284',
    code: 'British Virgin Islands (+1-284)',
  },
  {
    label_kr: '영국령 인도양 제도 (+246)',
    label_en: 'British Indian Ocean Territory (+246)',
    value: '+246',
    code: 'British Indian Ocean Territory (+246)',
  },
  {
    label_kr: '예멘 (+967)',
    label_en: 'Yemen (+967)',
    value: '+967',
    code: 'Yemen (+967)',
  },
  {
    label_kr: '오만 (+968)',
    label_en: 'Oman (+968)',
    value: '+968',
    code: 'Oman (+968)',
  },
  {
    label_kr: '오스트리아 (+43)',
    label_en: 'Austria (+43)',
    value: '+43',
    code: 'Austria (+43)',
  },
  {
    label_kr: '온두라스 (+504)',
    label_en: 'Honduras (+504)',
    value: '+504',
    code: 'Honduras (+504)',
  },
  {
    label_kr: '왈리스·퓌튀나 (+681)',
    label_en: 'Wallis and Futuna (+681)',
    value: '+681',
    code: 'Wallis and Futuna (+681)',
  },
  {
    label_kr: '요르단 (+962)',
    label_en: 'Jordan (+962)',
    value: '+962',
    code: 'Jordan (+962)',
  },
  {
    label_kr: '우간다 (+256)',
    label_en: 'Uganda (+256)',
    value: '+256',
    code: 'Uganda (+256)',
  },
  {
    label_kr: '우루과이 (+598)',
    label_en: 'Uruguay (+598)',
    value: '+598',
    code: 'Uruguay (+598)',
  },
  {
    label_kr: '우즈베키스탄 (+998)',
    label_en: 'Uzbekistan (+998)',
    value: '+998',
    code: 'Uzbekistan (+998)',
  },
  {
    label_kr: '우크라이나 (+380)',
    label_en: 'Ukraine (+380)',
    value: '+380',
    code: 'Ukraine (+380)',
  },
  {
    label_kr: '이라크 (+964)',
    label_en: 'Iraq (+964)',
    value: '+964',
    code: 'Iraq (+964)',
  },
  {
    label_kr: '이란 (+98)',
    label_en: 'Iran (+98)',
    value: '+98',
    code: 'Iran (+98)',
  },
  {
    label_kr: '이스라엘 (+972)',
    label_en: 'Israel (+972)',
    value: '+972',
    code: 'Israel (+972)',
  },
  {
    label_kr: '이집트 (+20)',
    label_en: 'Egypt (+20)',
    value: '+20',
    code: 'Egypt (+20)',
  },
  {
    label_kr: '이탈리아 (+39)',
    label_en: 'Italy (+39)',
    value: '+39',
    code: 'Italy (+39)',
  },
  {
    label_kr: '인도 (+91)',
    label_en: 'India (+91)',
    value: '+91',
    code: 'India (+91)',
  },
  {
    label_kr: '인도네시아 (+62)',
    label_en: 'Indonesia (+62)',
    value: '+62',
    code: 'Indonesia (+62)',
  },
  {
    label_kr: '일본 (+81)',
    label_en: 'Japan (+81)',
    value: '+81',
    code: 'Japan (+81)',
  },
  {
    label_kr: '자메이카 (+1-876)',
    label_en: 'Jamaica (+1-876)',
    value: '+1-876',
    code: 'Jamaica (+1-876)',
  },
  {
    label_kr: '잠비아 (+260)',
    label_en: 'Zambia (+260)',
    value: '+260',
    code: 'Zambia (+260)',
  },
  {
    label_kr: '저지 (+44)',
    label_en: 'Jersey (+44)',
    value: '+44',
    code: 'Jersey (+44)',
  },
  {
    label_kr: '적도기니 (+240)',
    label_en: 'Equatorial Guinea (+240)',
    value: '+240',
    code: 'Equatorial Guinea (+240)',
  },
  {
    label_kr: '조지아 (+995)',
    label_en: 'Georgia (+995)',
    value: '+995',
    code: 'Georgia (+995)',
  },
  {
    label_kr: '중국 (+86)',
    label_en: 'China (+86)',
    value: '+86',
    code: 'China (+86)',
  },
  {
    label_kr: '중앙아프리카공화국 (+236)',
    label_en: 'Central African Republic (+236)',
    value: '+236',
    code: 'Central African Republic (+236)',
  },
  {
    label_kr: '지부티 (+253)',
    label_en: 'Djibouti (+253)',
    value: '+253',
    code: 'Djibouti (+253)',
  },
  {
    label_kr: '지브롤터 (+350)',
    label_en: 'Gibraltar (+350)',
    value: '+350',
    code: 'Gibraltar (+350)',
  },
  {
    label_kr: '짐바브웨 (+263)',
    label_en: 'Zimbabwe (+263)',
    value: '+263',
    code: 'Zimbabwe (+263)',
  },
  {
    label_kr: '차드 (+235)',
    label_en: 'Chad (+235)',
    value: '+235',
    code: 'Chad (+235)',
  },
  {
    label_kr: '체코 (+420)',
    label_en: 'Czech Republic (+420)',
    value: '+420',
    code: 'Czech Republic (+420)',
  },
  {
    label_kr: '칠레 (+56)',
    label_en: 'Chile (+56)',
    value: '+56',
    code: 'Chile (+56)',
  },
  {
    label_kr: '카메룬 (+237)',
    label_en: 'Cameroon (+237)',
    value: '+237',
    code: 'Cameroon (+237)',
  },
  {
    label_kr: '카보베르데 (+238)',
    label_en: 'Cabo Verde (+238)',
    value: '+238',
    code: 'Cabo Verde (+238)',
  },
  {
    label_kr: '카자흐스탄 (+7)',
    label_en: 'Kazakhstan (+7)',
    value: '+7',
    code: 'Kazakhstan (+7)',
  },
  {
    label_kr: '카타르 (+974)',
    label_en: 'Qatar (+974)',
    value: '+974',
    code: 'Qatar (+974)',
  },
  {
    label_kr: '캄보디아 (+855)',
    label_en: 'Cambodia (+855)',
    value: '+855',
    code: 'Cambodia (+855)',
  },
  {
    label_kr: '캐나다 (+1)',
    label_en: 'Canada (+1)',
    value: '+1',
    code: 'Canada (+1)',
  },
  {
    label_kr: '케냐 (+254)',
    label_en: 'Kenya (+254)',
    value: '+254',
    code: 'Kenya (+254)',
  },
  {
    label_kr: '케이맨제도 (+1-345)',
    label_en: 'Cayman Islands (+1-345)',
    value: '+1-345',
    code: 'Cayman Islands (+1-345)',
  },
  {
    label_kr: '코모로 (+269)',
    label_en: 'Comoros (+269)',
    value: '+269',
    code: 'Comoros (+269)',
  },
  {
    label_kr: '코소보 (+383)',
    label_en: 'Kosovo (+383)',
    value: '+383',
    code: 'Kosovo (+383)',
  },
  {
    label_kr: '코스타리카 (+506)',
    label_en: 'Costa Rica (+506)',
    value: '+506',
    code: 'Costa Rica (+506)',
  },
  {
    label_kr: '코트디부아르 (+225)',
    label_en: "Côte d'Ivoire (+225)",
    value: '+225',
    code: "Côte d'Ivoire (+225)",
  },
  {
    label_kr: '콜롬비아 (+57)',
    label_en: 'Colombia (+57)',
    value: '+57',
    code: 'Colombia (+57)',
  },
  {
    label_kr: '콩고공화국 (+242)',
    label_en: 'Republic of the Congo (+242)',
    value: '+242',
    code: 'Republic of the Congo (+242)',
  },
  {
    label_kr: '콩고민주공화국(DR콩고) (+243)',
    label_en: 'Democratic Republic of the Congo (+243)',
    value: '+243',
    code: 'Democratic Republic of the Congo (+243)',
  },
  {
    label_kr: '쿠바 (+53)',
    label_en: 'Cuba (+53)',
    value: '+53',
    code: 'Cuba (+53)',
  },
  {
    label_kr: '쿠웨이트 (+965)',
    label_en: 'Kuwait (+965)',
    value: '+965',
    code: 'Kuwait (+965)',
  },
  {
    label_kr: '쿡제도 (+682)',
    label_en: 'Cook Islands (+682)',
    value: '+682',
    code: 'Cook Islands (+682)',
  },
  {
    label_kr: '크로아티아 (+385)',
    label_en: 'Croatia (+385)',
    value: '+385',
    code: 'Croatia (+385)',
  },
  {
    label_kr: '키르기즈 (+996)',
    label_en: 'Kyrgyzstan (+996)',
    value: '+996',
    code: 'Kyrgyzstan (+996)',
  },
  {
    label_kr: '키리바시 (+686)',
    label_en: 'Kiribati (+686)',
    value: '+686',
    code: 'Kiribati (+686)',
  },
  {
    label_kr: '타이완 (+886)',
    label_en: 'Taiwan (+886)',
    value: '+886',
    code: 'Taiwan (+886)',
  },
  {
    label_kr: '타지키스탄 (+992)',
    label_en: 'Tajikistan (+992)',
    value: '+992',
    code: 'Tajikistan (+992)',
  },
  {
    label_kr: '탄자니아 (+255)',
    label_en: 'Tanzania (+255)',
    value: '+255',
    code: 'Tanzania (+255)',
  },
  {
    label_kr: '태국 (+66)',
    label_en: 'Thailand (+66)',
    value: '+66',
    code: 'Thailand (+66)',
  },
  {
    label_kr: '터크스·케이커스 제도 (+1-649)',
    label_en: 'Turks and Caicos Islands (+1-649)',
    value: '+1-649',
    code: 'Turks and Caicos Islands (+1-649)',
  },
  {
    label_kr: '터키 (+90)',
    label_en: 'Turkey (+90)',
    value: '+90',
    code: 'Turkey (+90)',
  },
  {
    label_kr: '토고 (+228)',
    label_en: 'Togo (+228)',
    value: '+228',
    code: 'Togo (+228)',
  },
  {
    label_kr: '통가 (+676)',
    label_en: 'Tonga (+676)',
    value: '+676',
    code: 'Tonga (+676)',
  },
  {
    label_kr: '투르크메니스탄 (+993)',
    label_en: 'Turkmenistan (+993)',
    value: '+993',
    code: 'Turkmenistan (+993)',
  },
  {
    label_kr: '투발루 (+688)',
    label_en: 'Tuvalu (+688)',
    value: '+688',
    code: 'Tuvalu (+688)',
  },
  {
    label_kr: '튀니지 (+216)',
    label_en: 'Tunisia (+216)',
    value: '+216',
    code: 'Tunisia (+216)',
  },
  {
    label_kr: '트리니다드토바고 (+1-868)',
    label_en: 'Trinidad and Tobago (+1-868)',
    value: '+1-868',
    code: 'Trinidad and Tobago (+1-868)',
  },
  {
    label_kr: '파나마 (+507)',
    label_en: 'Panama (+507)',
    value: '+507',
    code: 'Panama (+507)',
  },
  {
    label_kr: '파라과이 (+595)',
    label_en: 'Paraguay (+595)',
    value: '+595',
    code: 'Paraguay (+595)',
  },
  {
    label_kr: '파키스탄 (+92)',
    label_en: 'Pakistan (+92)',
    value: '+92',
    code: 'Pakistan (+92)',
  },
  {
    label_kr: '파푸아뉴기니 (+675)',
    label_en: 'Papua New Guinea (+675)',
    value: '+675',
    code: 'Papua New Guinea (+675)',
  },
  {
    label_kr: '팔라우 (+680)',
    label_en: 'Palau (+680)',
    value: '+680',
    code: 'Palau (+680)',
  },
  {
    label_kr: '팔레스타인 (+970)',
    label_en: 'Palestine (+970)',
    value: '+970',
    code: 'Palestine (+970)',
  },
  {
    label_kr: '페루 (+51)',
    label_en: 'Peru (+51)',
    value: '+51',
    code: 'Peru (+51)',
  },
  {
    label_kr: '포르투갈 (+351)',
    label_en: 'Portugal (+351)',
    value: '+351',
    code: 'Portugal (+351)',
  },
  {
    label_kr: '폴란드 (+48)',
    label_en: 'Poland (+48)',
    value: '+48',
    code: 'Poland (+48)',
  },
  {
    label_kr: '푸에르토리코 (+1-1726)',
    label_en: 'Puerto Rico (+1-1726)',
    value: '+1-1726',
    code: 'Puerto Rico (+1-1726)',
  },
  {
    label_kr: '프랑스 (+33)',
    label_en: 'France (+33)',
    value: '+33',
    code: 'France (+33)',
  },
  {
    label_kr: '프랑스령 기아나 (+594)',
    label_en: 'French Guiana (+594)',
    value: '+594',
    code: 'French Guiana (+594)',
  },
  {
    label_kr: '프랑스령 폴리네시아 (+689)',
    label_en: 'French Polynesia (+689)',
    value: '+689',
    code: 'French Polynesia (+689)',
  },
  {
    label_kr: '피지 (+679)',
    label_en: 'Fiji (+679)',
    value: '+679',
    code: 'Fiji (+679)',
  },
  {
    label_kr: '핀란드 (+358)',
    label_en: 'Finland (+358)',
    value: '+358',
    code: 'Finland (+358)',
  },
  {
    label_kr: '필리핀 (+63)',
    label_en: 'Philippines (+63)',
    value: '+63',
    code: 'Philippines (+63)',
  },
  {
    label_kr: '핏케언 섬 (+64)',
    label_en: 'Pitcairn Islands (+64)',
    value: '+64',
    code: 'Pitcairn Islands (+64)',
  },
  {
    label_kr: '헝가리 (+36)',
    label_en: 'Hungary (+36)',
    value: '+36',
    code: 'Hungary (+36)',
  },
  {
    label_kr: '호주 (+61)',
    label_en: 'Australia (+61)',
    value: '+61',
    code: 'Australia (+61)',
  },
  {
    label_kr: '홍콩 (+852)',
    label_en: 'Hong Kong (+852)',
    value: '+852',
    code: 'Hong Kong (+852)',
  },
  {
    label_kr: '노퍽섬 (+672)',
    label_en: 'Norfolk Island (+672)',
    value: '+672',
    code: 'Norfolk Island (+672)',
  },
  {
    label_kr: '미국령 버진 아일랜드 (+1-340)',
    label_en: 'United States Virgin Islands (+1-340)',
    value: '+1-340',
    code: 'United States Virgin Islands (+1-340)',
  },
  {
    label_kr: '보네르 (+599)',
    label_en: 'Bonaire (+599)',
    value: '+599',
    code: 'Bonaire (+599)',
  },
  {
    label_kr: '부베섬 (+47)',
    label_en: 'Bouvet Island (+47)',
    value: '+47',
    code: 'Bouvet Island (+47)',
  },
  {
    label_kr: '사우스조지아 사우스샌드위치 제도 (+500)',
    label_en: 'South Georgia and the South Sandwich Islands (+500)',
    value: '+500',
    code: 'South Georgia and the South Sandwich Islands (+500)',
  },
  {
    label_kr: '세인트 마틴 (+590)',
    label_en: 'Saint Martin (+590)',
    value: '+590',
    code: 'Saint Martin (+590)',
  },
  {
    label_kr: '세인트 바르탤르미 (+590)',
    label_en: 'Saint Barthelemy (+590)',
    value: '+590',
    code: 'Saint Barthelemy (+590)',
  },
  {
    label_kr: '스발바르드 얀마이엔 제도 (+47)',
    label_en: 'Svalbard and Jan Mayen (+47)',
    value: '+47',
    code: 'Svalbard and Jan Mayen (+47)',
  },
  {
    label_kr: '신트마르텐 (+1-721)',
    label_en: 'Sint Maarten (+1-721)',
    value: '+1-721',
    code: 'Sint Maarten (+1-721)',
  },
  {
    label_kr: '아메리칸 사모아 (+1-684)',
    label_en: 'American Samoa (+1-684)',
    value: '+1-684',
    code: 'American Samoa (+1-684)',
  },
  {
    label_kr: '알랜드 군도 (+358)',
    label_en: 'Åland Islands (+358)',
    value: '+358',
    code: 'Åland Islands (+358)',
  },
  {
    label_kr: '유고슬라비아 (+380)',
    label_en: 'Yugoslavia (historical) (+380)',
    value: '+380',
    code: 'Yugoslavia (historical) (+380)',
  },
  {
    label_kr: '코코스 제도 (+61)',
    label_en: 'Cocos (Keeling) Islands (+61)',
    value: '+61',
    code: 'Cocos (Keeling) Islands (+61)',
  },
  {
    label_kr: '큐라소 (+599)',
    label_en: 'Curaçao (+599)',
    value: '+599',
    code: 'Curaçao (+599)',
  },
  {
    label_kr: '크리스마스섬 (+61)',
    label_en: 'Christmas Island (+61)',
    value: '+61',
    code: 'Christmas Island (+61)',
  },
  {
    label_kr: '토켈라우 (+690)',
    label_en: 'Tokelau (+690)',
    value: '+690',
    code: 'Tokelau (+690)',
  },
  {
    label_kr: '페로 군도 (+298)',
    label_en: 'Faroe Islands (+298)',
    value: '+298',
    code: 'Faroe Islands (+298)',
  },
  {
    label_kr: '포클랜드섬 (+500)',
    label_en: 'Falkland Islands (+500)',
    value: '+500',
    code: 'Falkland Islands (+500)',
  },
  {
    label_kr: '허드 맥도날드 군도 (+672)',
    label_en: 'Heard Island and McDonald Islands (+672)',
    value: '+672',
    code: 'Heard Island and McDonald Islands (+672)',
  },
]
